version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "twitter-tweets-analysis"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "url=\"\""
s3_prefix = "twitter-tweets-analysis"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14b7z0p4bsycx"
