AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Twitter Tweets Analysis

Parameters:
  url:
    Type: String
    Description: Link to HTML

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        KEY: hpAYD8Shnb2B2OHnCEUxQRSHu
        SECRET: Bg8a3o80jHf1gqX0OuK77owBSLpaYYhayhysHYgGOfj6Oma38S

Resources:
  ### Amplify ###
  TwitterTweetsAmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: TwitterTweetsAnalysis
      OauthToken: 5444f6d73cde38d32c73a18eebfb2502d9b8e785
      Repository: https://github.com/XinnyLiuu/twitter-tweets-analysis

  TwitterTweetsAmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: sandbox
      AppId: !GetAtt TwitterTweetsAmplifyApp.AppId
      EnableAutoBuild: true

  ### Lambda ###
  AnalyzeTweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "AnalyzeTweets"
      CodeUri: analyzeTweets/
      Handler: lambda.lambda_handler
      Runtime: python3.8
      Policies:
        # Give permission for Comprehend + Lambda + VPCs
        - ComprehendFullAccess
        - AWSLambdaFullAccess
        - AmazonVPCFullAccess
      Events:
        AnalyzeTweets:
          Type: Api
          Properties:
            Path: /analyze/tweets
            Method: post

  QueryNeptuneFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "QueryNeptune"
      CodeUri: queryNeptune/
      Handler: lambda.lambda_handler
      Runtime: python3.8
      Policies:
        # Give permission for Lambda + Neptune + VPC
        - AWSLambdaFullAccess
        - NeptuneFullAccess
        - AmazonVPCFullAccess

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  AnalyzeTweetsApi:
    Description: "API Gateway endpoint URL for Prod stage for Analyze Tweets function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze/tweets"

  AnalyzeTweetsFunction:
    Description: "Analyze Tweets Lambda Function ARN"
    Value: !GetAtt AnalyzeTweetsFunction.Arn

  QueryNeptuneFunction:
    Description: "Query Neptune with Entities extraced from Comprehend"
    Value: !GetAtt QueryNeptuneFunction.Arn

  AnalyzeTweetsFunctionIamRole:
    Description: "Implicit IAM Role created for Analyze Tweets function"
    Value: !GetAtt AnalyzeTweetsFunction.Arn

  TwitterTweetsAmplifyDomain:
    Description: "Domain for deployed app"
    Value: !GetAtt TwitterTweetsAmplifyApp.DefaultDomain
