AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Twitter Tweets Analysis

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        NEPTUNE_ENDPOINT: !GetAtt TweetsEntitiesNeptuneInstance.Endpoint
        KEY: hpAYD8Shnb2B2OHnCEUxQRSHu
        SECRET: Bg8a3o80jHf1gqX0OuK77owBSLpaYYhayhysHYgGOfj6Oma38S

Resources:
#  ### Amplify ###
#  TwitterTweetsAmplifyApp:
#    Type: AWS::Amplify::App
#    Properties:
#      Name: TwitterTweetsAnalysis
#      OauthToken: <>
#      Repository: https://github.com/XinnyLiuu/twitter-tweets-analysis
#
#  TwitterTweetsAmplifyBranch:
#    Type: AWS::Amplify::Branch
#    Properties:
#      BranchName: sandbox
#      AppId: !GetAtt TwitterTweetsAmplifyApp.AppId
#      EnableAutoBuild: true

  ### Lambda ###
  AnalyzeTweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "AnalyzeTweets"
      CodeUri: analyzeTweets/
      Handler: lambda.lambda_handler
      Runtime: python3.8
      Policies:
        # Give permission for Comprehend + Lambda + VPCs
        - ComprehendFullAccess
        - AWSLambdaFullAccess
        - AmazonVPCFullAccess
      Events:
        AnalyzeTweets:
          Type: Api
          Properties:
            Path: /analyze
            Method: post

  AddTermToNeptuneFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "AddTermToNeptune"
      CodeUri: addTermToNeptune/
      Handler: lambda.lambda_handler
      Runtime: python3.8
      Policies:
        # Give permission for Lambda + Neptune + VPCs
        - AWSLambdaFullAccess
        - NeptuneFullAccess
        - AmazonVPCFullAccess
      VpcConfig:
        SecurityGroupIds: # Look for your default security group 'console -> VPC -> Security Groups'
          - "sg-5c705962"
        SubnetIds: # Look for your default security group 'console -> VPC -> Subnets'
          - "subnet-0854ad39"
          - "subnet-3ab6d934"
          - "subnet-3b20901a"
          - "subnet-8ab401ec"
          - "subnet-d054e28f"
          - "subnet-e2c287af"

  GetGraphFromNeptuneFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "GetGraphFromNeptune"
      CodeUri: getGraphFromNeptune/
      Handler: lambda.lambda_handler
      Runtime: python3.8
      Policies:
        # Give permission for Lambda + Neptune + VPCs
        - AWSLambdaFullAccess
        - NeptuneFullAccess
        - AmazonVPCFullAccess
      VpcConfig:
        SecurityGroupIds: # Look for your default security group 'console -> VPC -> Security Groups'
          - "sg-5c705962"
        SubnetIds: # Look for your default security group 'console -> VPC -> Subnets'
          - "subnet-0854ad39"
          - "subnet-3ab6d934"
          - "subnet-3b20901a"
          - "subnet-8ab401ec"
          - "subnet-d054e28f"
          - "subnet-e2c287af"
      Events:
        GetGraphFromNeptune:
          Type: Api
          Properties:
            Path: /neptune
            Method: post

  ### Neptune ###
  TweetsEntitiesNeptuneCluster:
    Type: AWS::Neptune::DBCluster
    Properties:
      VpcSecurityGroupIds: [ "sg-5c705962" ] # Look for your default security group 'console -> VPC -> Security Groups'

  TweetsEntitiesNeptuneInstance:
    Type: AWS::Neptune::DBInstance
    Properties:
      DBClusterIdentifier: !Ref TweetsEntitiesNeptuneCluster
      DBInstanceClass: "db.t3.medium" # Smallest available instance

Outputs:
  #  TwitterTweetsAmplifyDomain:
  #    Description: "Domain for deployed app"
  #    Value: !GetAtt TwitterTweetsAmplifyApp.DefaultDomain

  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  AnalyzeTweetsEndpoint:
    Description: "Endpoint for analyzing tweets"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze"

  GetGraphFromNeptuneEndpoint:
    Description: "Endpoint for retrieving data from neptune to build a graph"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/neptune"

  AnalyzeTweetsFunction:
    Description: "Analyze Tweets Lambda Function ARN"
    Value: !GetAtt AnalyzeTweetsFunction.Arn

  AddTermToNeptuneFunction:
    Description: "Creates vertices for a term and its entities in Neptune"
    Value: !GetAtt AddTermToNeptuneFunction.Arn

  GetGraphFromNeptuneFunction:
    Description: "Gets all entities that are related to a term from Neptune"
    Value: !GetAtt GetGraphFromNeptuneFunction.Arn

  TweetsEntitiesNeptuneInstanceEndpoint:
    Description: "Neptune cluster that contains the term and its entities"
    Value: !GetAtt TweetsEntitiesNeptuneInstance.Endpoint