AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Twitter Tweets Analysis

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        KEY: hpAYD8Shnb2B2OHnCEUxQRSHu
        SECRET: Bg8a3o80jHf1gqX0OuK77owBSLpaYYhayhysHYgGOfj6Oma38S

Resources:
#  ### Amplify ###
#  TwitterTweetsAmplifyApp:
#    Type: AWS::Amplify::App
#    Properties:
#      Name: TwitterTweetsAnalysis
#      OauthToken: <>
#      Repository: https://github.com/XinnyLiuu/twitter-tweets-analysis
#
#  TwitterTweetsAmplifyBranch:
#    Type: AWS::Amplify::Branch
#    Properties:
#      BranchName: sandbox
#      AppId: !GetAtt TwitterTweetsAmplifyApp.AppId
#      EnableAutoBuild: true

  ### Lambda ###
  AnalyzeTweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "AnalyzeTweets"
      CodeUri: analyzeTweets/
      Handler: lambda.lambda_handler
      Runtime: python3.8
      Policies:
        # Give permission for Comprehend + Lambda + VPCs
        - ComprehendFullAccess
        - AWSLambdaFullAccess
        - AmazonVPCFullAccess
      Events:
        AnalyzeTweets:
          Type: Api
          Properties:
            Path: /analyze
            Method: post

  AddTermToNeptuneFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "AddTermToNeptune"
      CodeUri: addTermToNeptune/
      Handler: lambda.lambda_handler
      Runtime: python3.8
      Policies:
        # Give permission for Lambda + Neptune + VPCs
        - AWSLambdaFullAccess
        - NeptuneFullAccess
        - AmazonVPCFullAccess

  GetGraphFromNeptuneFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "GetGraphFromNeptune"
      CodeUri: getGraphFromNeptune/
      Handler: lambda.lambda_handler
      Runtime: python3.8
      Policies:
        # Give permission for Lambda + Neptune + VPCs
        - AWSLambdaFullAccess
        - NeptuneFullAccess
        - AmazonVPCFullAccess
      Events:
        GetGraphFromNeptune:
          Type: Api
          Properties:
            Path: /neptune
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  AnalyzeTweetsApi:
    Description: "Endpoint for analyzing tweets"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze"

  GetGraphFromNeptuneApi:
    Description: "Endpoint for retrieving data from neptune to build a graph"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/neptune"

  AnalyzeTweetsFunction:
    Description: "Analyze Tweets Lambda Function ARN"
    Value: !GetAtt AnalyzeTweetsFunction.Arn

  AddTermToNeptuneFunction:
    Description: "Creates vertices for a term and its entities in Neptune"
    Value: !GetAtt AddTermToNeptuneFunction.Arn

  GetGraphFromNeptuneFunction:
    Description: "Gets all entities that are related to a term from Neptune"
    Value: !GetAtt GetGraphFromNeptuneFunction.Arn

#  TwitterTweetsAmplifyDomain:
#    Description: "Domain for deployed app"
#    Value: !GetAtt TwitterTweetsAmplifyApp.DefaultDomain